services:
  web:
    volumes:
      - app_public:/app/public
  app:
    build:
      target: prod
    image: registry.$DOMAIN_NAME/laravel-nginx-prod
    volumes:
      - app_public:/app/public
volumes:
  app_public:
