services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_IMAGE:
    image: $APP_IMAGE
    volumes:
      - ./etc/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - 80:80
