services:
  web:
    depends_on:
      - app
    image: $NGINX_VERSION
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - app_public:/app/public
      - var_run:/var/run
    ports:
      - 80:80
  app:
    build:
      target: prod
    volumes:
      - app_public:/app/public
      - var_run:/var/run
volumes:
  app_public:
  var_run:
