ARG RUBY_VERSION

FROM $RUBY_VERSION AS base

RUN apk add build-base shared-mime-info tzdata\
  nodejs yarn\
  sqlite-dev\
  mysql-client mysql-dev\
  postgresql-dev\
  && rm -rf /var/cache/apk/

ARG RAILS_VERSION

RUN gem install rails -v $RAILS_VERSION

WORKDIR /app

EXPOSE 3000

ENTRYPOINT [ "bundle" ]

FROM base AS dev

CMD [ "install", "npm i", "rails server -b 0.0.0.0" ]

FROM dev AS build

COPY ./src .

FROM base AS prod

COPY --from=build /app .

RUN bundle install\
  && rm config/credentials.yml.enc\
  && EDITOR="mate --wait" rails credentials:edit

ENV RAILS_ENV=production
RUN rake assets:precompile

ENV RAILS_SERVE_STATIC_FILES=true
CMD [ "exec puma -e production -b unix:///var/run/puma.sock" ]
