ARG COMPOSER_IMAGE=composer:2.10.2
ARG PHP_IMAGE=php:8.5.10-fpm-alpine

#composer version
FROM $COMPOSER_IMAGE AS composer

FROM $PHP_IMAGE AS base

#dependencies
RUN apk add --no-cache libzip-dev
  
#extensions
RUN docker-php-ext-install -j$(nproc) zip

WORKDIR /var/www/html

FROM base AS dev

#dev dependencies
RUN apk add git unzip wget bash\
  && rm -rf /var/cache/apk/

#composer
COPY --from=composer /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER=1

#symfony
RUN  curl -fsSL https://get.symfony.com/cli/installer | bash\
  && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

RUN cp $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini\
&& sed -i '\
s/;opcache.enable=.*/opcache.enable=1/;\
s/;opcache.enable_cli=.*/opcache.enable_cli=1/;\
s|;date.timezone =.*|date.timezone = Europe/Paris|;\
s/memory_limit =.*/memory_limit = 128M/;\
' $PHP_INI_DIR/php.ini

FROM dev AS build

COPY src .

ARG APP_ENV
ARG APP_DEBUG
ARG APP_SECRET
ARG DATABASE_URL

RUN composer install --no-dev --optimize-autoloader\
  && composer dump-autoload --no-dev --classmap-authoritative\
  && composer dump-env prod --empty

RUN bin/console cache:warmup

FROM base AS prod

COPY --from=build /var/www/html .

RUN chown -R nobody:nogroup var

RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini\
&& sed -i '\
s/;opcache.enable=.*/opcache.enable=1/;\
s/;opcache.enable_cli=.*/opcache.enable_cli=1/;\
s/;opcache.memory_consumption=.*/opcache.memory_consumption=256/;\
s/;opcache.max_accelerated_files=.*/opcache.max_accelerated_files=20000/;\
s/;opcache.validate_timestamps=.*/opcache.validate_timestamps=0/;\
s/;opcache.interned_strings_buffer=.*/opcache.interned_strings_buffer=16/;\
s|;opcache.preload=.*|opcache.preload=/var/www/html/vendor/preload.php|;\
s/;opcache.preload_user=.*/opcache.preload_user=nobody/;\
' $PHP_INI_DIR/php.ini\
&& echo 'opcache.jit_buffer_size=100M' >> $PHP_INI_DIR/php.ini\
&& sed -i '\
s/;realpath_cache_size =.*/realpath_cache_size = 4096k/;\
s/;realpath_cache_ttl =.*/realpath_cache_ttl = 600/;\
s|;date.timezone =.*|date.timezone = Europe/Paris|;\
s/memory_limit =.*/memory_limit = 128M/;\
s/display_errors =.*/display_errors = Off/;\
' $PHP_INI_DIR/php.ini
